import type { Producer, Product, Order, Review } from "./types";

export const MOCK_PRODUCERS: Producer[] = [
  {
    id: "producer-1",
    userId: "user-1",
    name: "Greenfield Farm",
    slug: "greenfield-farm",
    bio: "Third-generation family farm nestled in the Vale of Belvoir. We grow over 40 varieties of seasonal vegetables using traditional and sustainable methods.",
    story:
      "My grandfather started this farm in 1962 with just two acres and a dream. Today we farm 85 acres of some of the most fertile land in Lincolnshire, feeding families across the East Midlands.",
    location: "Vale of Belvoir, Lincolnshire",
    address: {
      line1: "Greenfield Farm, Long Lane",
      city: "Grantham",
      county: "Lincolnshire",
      postcode: "NG31 7AA",
      country: "GB",
    },
    categories: ["vegetables", "fruit", "plants"],
    images: {
      banner:
        "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1400&q=80",
      logo: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=200&q=80",
    },
    status: "approved",
    commissionRate: 0.1,
    fulfilmentOptions: ["ship", "collect"],
    socialLinks: { instagram: "@greenfieldfarm" },
    rating: 4.9,
    reviewCount: 142,
    createdAt: new Date("2023-03-15"),
  },
  {
    id: "producer-2",
    userId: "user-2",
    name: "Meadowsweet Dairy",
    slug: "meadowsweet-dairy",
    bio: "Award-winning artisan dairy producing handcrafted cheeses, fresh yoghurt, and rich cream from our herd of 40 Jersey cows.",
    story:
      "Our Jerseys have been roaming the Charnwood Forest hills for 30 years. The exceptional richness of their milk comes through in every product — it's why our aged cheddar has won Great Taste Awards three years running.",
    location: "Charnwood Forest, Leicestershire",
    address: {
      line1: "Meadowsweet Farm",
      city: "Loughborough",
      county: "Leicestershire",
      postcode: "LE12 8TN",
      country: "GB",
    },
    categories: ["dairy"],
    images: {
      banner:
        "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=1400&q=80",
      logo: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=200&q=80",
    },
    status: "approved",
    commissionRate: 0.1,
    fulfilmentOptions: ["ship", "collect", "consolidate"],
    socialLinks: {
      instagram: "@meadowsweetdairy",
      facebook: "MeadowsweetDairy",
    },
    rating: 4.8,
    reviewCount: 98,
    createdAt: new Date("2023-04-02"),
  },
  {
    id: "producer-3",
    userId: "user-3",
    name: "The Village Bakehouse",
    slug: "village-bakehouse",
    bio: "Wood-fired sourdoughs, heritage grain loaves, and seasonal pastries baked fresh every morning in a traditional stone bakehouse.",
    story:
      "We source our grain from a single estate mill in Derbyshire, and every loaf is slow-fermented for 36 hours. You can taste the difference.",
    location: "Matlock, Derbyshire",
    address: {
      line1: "14 Church Street",
      city: "Matlock",
      county: "Derbyshire",
      postcode: "DE4 3BZ",
      country: "GB",
    },
    categories: ["bakery"],
    images: {
      banner:
        "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1400&q=80",
      logo: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=200&q=80",
    },
    status: "approved",
    commissionRate: 0.12,
    fulfilmentOptions: ["collect", "consolidate"],
    rating: 5.0,
    reviewCount: 67,
    createdAt: new Date("2023-05-10"),
  },
  {
    id: "producer-4",
    userId: "user-4",
    name: "Wildwood Honey",
    slug: "wildwood-honey",
    bio: "Raw, unfiltered honey from 80 hives across the Sherwood Forest margins. Single-varietal and wildflower blends, all cold-extracted to preserve enzymes.",
    story:
      "I stumbled into beekeeping after retiring from the NHS. Twelve years later we have 80 hives and supply some of the finest restaurants in Nottingham.",
    location: "Sherwood Forest, Nottinghamshire",
    address: {
      line1: "Forest Edge Cottage",
      city: "Ollerton",
      county: "Nottinghamshire",
      postcode: "NG22 9AJ",
      country: "GB",
    },
    categories: ["honey", "preserves"],
    images: {
      banner:
        "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1400&q=80",
      logo: "https://images.unsplash.com/photo-1471943311424-646960669fbc?w=200&q=80",
    },
    status: "approved",
    commissionRate: 0.12,
    fulfilmentOptions: ["ship", "collect"],
    rating: 4.7,
    reviewCount: 203,
    createdAt: new Date("2023-02-28"),
  },
  {
    id: "producer-5",
    userId: "user-5",
    name: "Riverside Rare Breeds",
    slug: "riverside-rare-breeds",
    bio: "Pasture-raised rare breed beef, pork, and lamb. Slow-grown for superior flavour on water meadows along the River Trent.",
    story:
      "We raise Dexter cattle, Oxford Sandy & Black pigs, and Herdwick sheep the way nature intended — on grass, with space, and with patience. Our animals live twice as long as commercial breeds.",
    location: "Trent Valley, Nottinghamshire",
    address: {
      line1: "Riverside Farm",
      city: "Newark",
      county: "Nottinghamshire",
      postcode: "NG24 3BQ",
      country: "GB",
    },
    categories: ["meat"],
    images: {
      banner:
        "https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=1400&q=80",
      logo: "https://images.unsplash.com/photo-1560781290-7dc94c0f8f4f?w=200&q=80",
    },
    status: "approved",
    commissionRate: 0.1,
    fulfilmentOptions: ["ship", "collect"],
    rating: 4.9,
    reviewCount: 55,
    createdAt: new Date("2023-06-01"),
  },
  {
    id: "producer-6",
    userId: "user-6",
    name: "Bramble & Berry Preserves",
    slug: "bramble-berry-preserves",
    bio: "Small-batch jams, chutneys, cordials, and pickles made with foraged and locally grown fruit. No artificial preservatives, ever.",
    story:
      "Every July I close my kitchen and spend two weeks foraging elderberries, sloe berries, and wild plums from the hedgerows around our village. The rest of the year, I turn them into something magical.",
    location: "Peak District fringe, Derbyshire",
    address: {
      line1: "Rose Cottage",
      city: "Bakewell",
      county: "Derbyshire",
      postcode: "DE45 1EE",
      country: "GB",
    },
    categories: ["preserves", "drinks"],
    images: {
      banner:
        "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=1400&q=80",
      logo: "https://images.unsplash.com/photo-1542838686-7a7b9c3f5f89?w=200&q=80",
    },
    status: "approved",
    commissionRate: 0.12,
    fulfilmentOptions: ["ship", "collect"],
    rating: 4.8,
    reviewCount: 178,
    createdAt: new Date("2023-03-20"),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    producerId: "producer-1",
    producerName: "Greenfield Farm",
    producerSlug: "greenfield-farm",
    name: "Mixed Seasonal Veg Box",
    description:
      "A curated selection of whatever is growing best this week — typically 8–10 varieties including roots, greens, and alliums. Each box feeds a family of four for the week.",
    slug: "mixed-seasonal-veg-box",
    category: "vegetables",
    price: 1850,
    unit: "box",
    stock: 24,
    images: [
      "https://images.unsplash.com/photo-1518977676405-7a4e0b3e84c5?w=800&q=80",
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&q=80",
    ],
    dietary: ["vegan", "organic"],
    allergens: [],
    seasonal: true,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "prod-2",
    producerId: "producer-1",
    producerName: "Greenfield Farm",
    producerSlug: "greenfield-farm",
    name: "Heritage Tomatoes (Mixed)",
    description:
      "A rainbow of heirloom varieties — Brandywine, Black Krim, Green Zebra, and more. Grown slowly for complex flavour you simply cannot buy in a supermarket.",
    slug: "heritage-tomatoes",
    category: "vegetables",
    price: 495,
    unit: "500g",
    stock: 60,
    images: [
      "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&q=80",
    ],
    dietary: ["vegan", "organic"],
    allergens: [],
    seasonal: true,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "prod-3",
    producerId: "producer-2",
    producerName: "Meadowsweet Dairy",
    producerSlug: "meadowsweet-dairy",
    name: "Aged Jersey Cheddar",
    description:
      "18-month cave-aged cheddar from our Jersey herd. Dense, crumbly, with rich butterscotch notes and a long savoury finish. Great Taste Award winner 2024.",
    slug: "aged-jersey-cheddar",
    category: "dairy",
    price: 895,
    unit: "250g",
    stock: 40,
    images: [
      "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=800&q=80",
    ],
    dietary: ["vegetarian", "gluten-free"],
    allergens: ["milk"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-12"),
  },
  {
    id: "prod-4",
    producerId: "producer-2",
    producerName: "Meadowsweet Dairy",
    producerSlug: "meadowsweet-dairy",
    name: "Whole Milk Natural Yoghurt",
    description:
      "Set in the pot from single-herd Jersey milk. Thick, creamy, and gently tart. No thickeners, no additives — just milk and live cultures.",
    slug: "whole-milk-yoghurt",
    category: "dairy",
    price: 325,
    unit: "500ml",
    stock: 80,
    images: [
      "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80",
    ],
    dietary: ["vegetarian", "gluten-free"],
    allergens: ["milk"],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-01-12"),
  },
  {
    id: "prod-5",
    producerId: "producer-3",
    producerName: "The Village Bakehouse",
    producerSlug: "village-bakehouse",
    name: "Country Sourdough Loaf",
    description:
      "Long-fermented sourdough made with stoneground heritage wheat. Open crumb, blistered crust, and complex tang from our 12-year-old starter.",
    slug: "country-sourdough",
    category: "bakery",
    price: 675,
    unit: "800g loaf",
    stock: 20,
    images: [
      "https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=800&q=80",
    ],
    dietary: ["vegan"],
    allergens: ["gluten"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "prod-6",
    producerId: "producer-3",
    producerName: "The Village Bakehouse",
    producerSlug: "village-bakehouse",
    name: "Rye & Caraway Loaf",
    description:
      "Dense, moist 70% rye loaf with toasted caraway seeds. Exceptional with smoked salmon, strong cheese, or just good butter.",
    slug: "rye-caraway-loaf",
    category: "bakery",
    price: 595,
    unit: "650g loaf",
    stock: 15,
    images: [
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80",
    ],
    dietary: ["vegan"],
    allergens: ["gluten"],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "prod-7",
    producerId: "producer-4",
    producerName: "Wildwood Honey",
    producerSlug: "wildwood-honey",
    name: "Sherwood Forest Wildflower Honey",
    description:
      "Raw, cold-extracted wildflower honey from hives set among heather, clover, and bramble on the Sherwood Forest margins. Crystallises naturally to a smooth, spreadable set.",
    slug: "wildflower-honey",
    category: "honey",
    price: 850,
    unit: "340g jar",
    stock: 120,
    images: [
      "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&q=80",
    ],
    dietary: ["gluten-free", "dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "prod-8",
    producerId: "producer-5",
    producerName: "Riverside Rare Breeds",
    producerSlug: "riverside-rare-breeds",
    name: "Dexter Beef Mince",
    description:
      "Rich, deeply flavoured mince from slow-grown Dexter cattle. Higher fat marbling than commercial beef — ideal for burgers, bolognese, or cottage pie.",
    slug: "dexter-beef-mince",
    category: "meat",
    price: 895,
    unit: "500g",
    stock: 35,
    images: [
      "https://images.unsplash.com/photo-1588168333986-5078d3ae3976?w=800&q=80",
    ],
    dietary: ["gluten-free", "dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "prod-9",
    producerId: "producer-6",
    producerName: "Bramble & Berry Preserves",
    producerSlug: "bramble-berry-preserves",
    name: "Wild Sloe & Damson Jam",
    description:
      "Foraged sloe berries and locally grown damsons cooked low and slow with a touch of vanilla. Dark, intensely fruity, and just sharp enough to cut through cream or butter.",
    slug: "sloe-damson-jam",
    category: "preserves",
    price: 550,
    unit: "220g jar",
    stock: 85,
    images: [
      "https://images.unsplash.com/photo-1542838686-7a7b9c3f5f89?w=800&q=80",
    ],
    dietary: ["vegan", "gluten-free", "dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-08"),
  },
  {
    id: "prod-10",
    producerId: "producer-1",
    producerName: "Greenfield Farm",
    producerSlug: "greenfield-farm",
    name: "Tenderstem Broccoli",
    description:
      "Crisp, sweet tenderstem broccoli harvested same morning. Cut-to-order, bunched by hand, and delivered within 24 hours.",
    slug: "tenderstem-broccoli",
    category: "vegetables",
    price: 275,
    unit: "250g bunch",
    stock: 100,
    images: [
      "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=800&q=80",
    ],
    dietary: ["vegan", "organic"],
    allergens: [],
    seasonal: true,
    available: true,
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "prod-11",
    producerId: "producer-2",
    producerName: "Meadowsweet Dairy",
    producerSlug: "meadowsweet-dairy",
    name: "Free-Range Eggs (dozen)",
    description:
      "Deep-orange yolked eggs from our heritage breed hens. Fed on a mixed grain ration and given free range over the farm fields.",
    slug: "free-range-eggs",
    category: "dairy",
    price: 395,
    unit: "dozen",
    stock: 60,
    images: [
      "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=800&q=80",
    ],
    dietary: ["vegetarian", "gluten-free", "dairy-free", "free-range"],
    allergens: ["eggs"],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-01-12"),
  },
  {
    id: "prod-12",
    producerId: "producer-4",
    producerName: "Wildwood Honey",
    producerSlug: "wildwood-honey",
    name: "Heather Honey",
    description:
      "Single-varietal late-summer heather honey with a deep amber colour and thixotropic set. Intense, aromatic, and prized by connoisseurs.",
    slug: "heather-honey",
    category: "honey",
    price: 1250,
    unit: "340g jar",
    stock: 40,
    images: [
      "https://images.unsplash.com/photo-1471943311424-646960669fbc?w=800&q=80",
    ],
    dietary: ["gluten-free", "dairy-free"],
    allergens: [],
    seasonal: true,
    available: true,
    createdAt: new Date("2024-01-05"),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    orderId: "order-1",
    consumerId: "consumer-1",
    consumerName: "Sarah M.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "Best veg box I've ever had. Everything was incredibly fresh and the variety was brilliant. The heritage tomatoes were a revelation.",
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "rev-2",
    orderId: "order-2",
    consumerId: "consumer-2",
    consumerName: "James T.",
    producerId: "producer-2",
    rating: 5,
    comment:
      "The cheddar is extraordinary. I bought it thinking it would be a nice treat — it's now a permanent fixture in my fridge. Worth every penny.",
    createdAt: new Date("2024-02-12"),
  },
  {
    id: "rev-3",
    orderId: "order-3",
    consumerId: "consumer-3",
    consumerName: "Emma R.",
    producerId: "producer-3",
    rating: 5,
    comment:
      "The sourdough is on another level. You can genuinely taste the difference from supermarket bread. I've been ordering every week since.",
    createdAt: new Date("2024-02-18"),
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "order-demo-1",
    consumerId: "consumer-1",
    consumerName: "Demo User",
    items: [
      {
        productId: "prod-1",
        productName: "Mixed Seasonal Veg Box",
        producerId: "producer-1",
        producerName: "Greenfield Farm",
        price: 1850,
        quantity: 1,
        unit: "box",
        imageUrl:
          "https://images.unsplash.com/photo-1518977676405-7a4e0b3e84c5?w=400&q=80",
      },
      {
        productId: "prod-3",
        productName: "Aged Jersey Cheddar",
        producerId: "producer-2",
        producerName: "Meadowsweet Dairy",
        price: 895,
        quantity: 2,
        unit: "250g",
        imageUrl:
          "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&q=80",
      },
    ],
    producerIds: ["producer-1", "producer-2"],
    status: "delivered",
    fulfilmentMethod: "delivery",
    deliveryAddress: {
      line1: "12 Market Square",
      city: "Nottingham",
      postcode: "NG1 2DT",
      country: "GB",
    },
    subtotal: 3640,
    commission: 437,
    deliveryFee: 395,
    total: 4035,
    stripePaymentIntentId: "pi_demo_001",
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-13"),
  },
];
