import type { Producer, Product, Order, Review } from "./types";

export const MOCK_PRODUCERS: Producer[] = [
  {
    id: "producer-1",
    userId: "user-1",
    name: "Fieldgate Farm Shop",
    slug: "fieldgate-farm-shop",
    bio: "Eight-acre market garden in Market Harborough growing over 60 varieties of seasonal vegetable, salad, and herb. Harvested the morning it's dispatched — no cold storage, no middlemen, no compromise.",
    story:
      "My wife and I left careers in London in 2009 to grow vegetables properly. We'd both grown up with allotments and we were frustrated by how hard it was to buy produce that actually tasted of anything. We leased eight acres on a south-facing slope outside Market Harborough and started with a small polytunnel and a list of varieties we wanted to grow. Fifteen years later the farm has expanded to include three polytunnels, an outdoor growing area, a small orchard, and a kitchen garden where we trial new varieties every season. We grow over 60 different vegetables, salads, and herbs — some familiar, many that you simply can't find in supermarkets. Heritage tomatoes, rainbow chard, French breakfast radishes, cavolo nero, purple sprouting broccoli, eight varieties of courgette. Everything is grown using no-dig methods with homemade compost. We harvest early on dispatch mornings so that everything goes from field to your door within 24 hours. The difference in flavour compared to supermarket produce — even 'fresh' supermarket produce — is extraordinary.",
    location: "Market Harborough, Leicestershire",
    address: {
      line1: "Fieldgate Farm, Lubenham Hill",
      city: "Market Harborough",
      county: "Leicestershire",
      postcode: "LE16 9TQ",
      country: "GB",
    },
    categories: ["vegetables", "salads", "preserves"],
    images: {
      banner: "/images/hero.jpg",
      logo: "/images/heritage-tomatoes.jpg",
    },
    status: "approved",
    commissionRate: 0,
    fulfilmentOptions: ["ship", "collect"],
    socialLinks: {
      instagram: "@fieldgatefarm",
      facebook: "FieldgateFarm",
    },
    rating: 4.9,
    reviewCount: 836,
    createdAt: new Date("2009-04-01"),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    producerId: "producer-1",
    producerName: "Fieldgate Farm Shop",
    producerSlug: "fieldgate-farm-shop",
    name: "Weekly Seasonal Veg Box (large)",
    description:
      "A large box of whatever is at its absolute best this week — typically 10–12 different vegetables, harvested the morning of dispatch. No repeats two weeks running. Includes a weekly recipe card written around what's in the box. Serves a family of four for the week.",
    slug: "weekly-seasonal-veg-box-large",
    category: "vegetables",
    price: 2200,
    unit: "large box (10–12 items, serves 4)",
    stock: 60,
    images: [
      "/images/veg-box.jpg",
    ],
    dietary: ["vegan", "gluten-free", "dairy-free"],
    allergens: [],
    seasonal: true,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "prod-2",
    producerId: "producer-1",
    producerName: "Fieldgate Farm Shop",
    producerSlug: "fieldgate-farm-shop",
    name: "Heritage Tomato Selection (500g)",
    description:
      "A mixed punnet of whatever heritage tomato varieties are at peak ripeness this week — typically 4–6 different types including Brandywine, Black Krim, Green Zebra, and Tigerella. All vine-ripened on the plant, never chilled. The flavour difference compared to commercial tomatoes is genuinely shocking.",
    slug: "heritage-tomato-selection-500g",
    category: "vegetables",
    price: 450,
    unit: "500g mixed selection",
    stock: 40,
    images: [
      "/images/heritage-tomatoes.jpg",
    ],
    dietary: ["vegan", "gluten-free", "dairy-free"],
    allergens: [],
    seasonal: true,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "prod-3",
    producerId: "producer-1",
    producerName: "Fieldgate Farm Shop",
    producerSlug: "fieldgate-farm-shop",
    name: "Free-Range Eggs (dozen)",
    description:
      "A dozen eggs from our small flock of 40 hens — a mix of breeds chosen for flavour and yolk colour rather than productivity. They range across the orchard year-round, eating grass, bugs, and kitchen scraps. Deep orange yolks, rich flavour, and shells that actually feel like eggs.",
    slug: "free-range-eggs-dozen",
    category: "vegetables",
    price: 450,
    unit: "dozen eggs",
    stock: 50,
    images: [
      "/images/eggs.jpg",
    ],
    dietary: ["gluten-free", "dairy-free"],
    allergens: ["eggs"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "prod-4",
    producerId: "producer-1",
    producerName: "Fieldgate Farm Shop",
    producerSlug: "fieldgate-farm-shop",
    name: "Wild Garlic Pesto (180g)",
    description:
      "Made each April when our hedgerows are full of wild garlic. Raw wild garlic leaves, Parmesan, toasted pine nuts, and Sicilian olive oil — blended and jarred the same day. Intense, green, and pungent in the best possible way. Available for 6 weeks only each year.",
    slug: "wild-garlic-pesto-180g",
    category: "preserves",
    price: 650,
    unit: "180g jar",
    stock: 30,
    images: [
      "https://images.unsplash.com/photo-1518843875459-f738682238a6?w=800&q=80",
    ],
    dietary: ["gluten-free", "vegetarian"],
    allergens: ["dairy", "nuts"],
    seasonal: true,
    available: true,
    featured: true,
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "prod-5",
    producerId: "producer-1",
    producerName: "Fieldgate Farm Shop",
    producerSlug: "fieldgate-farm-shop",
    name: "Mixed Salad Leaves (bag)",
    description:
      "A generous bag of mixed salad leaves cut fresh that morning — typically 8–10 varieties including rocket, mizuna, mustard frills, baby spinach, and whatever else is ready in the polytunnel. Washed, dried, and bagged. The difference from supermarket bags, even premium ones, is immediately obvious.",
    slug: "mixed-salad-leaves-bag",
    category: "salads",
    price: 300,
    unit: "approx. 120g bag",
    stock: 70,
    images: [
      "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80",
    ],
    dietary: ["vegan", "gluten-free", "dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "prod-6",
    producerId: "producer-1",
    producerName: "Fieldgate Farm Shop",
    producerSlug: "fieldgate-farm-shop",
    name: "Rainbow Chard Bunch",
    description:
      "A generous bunch of rainbow chard — stems in red, yellow, orange, and white, with deep green leaves. Grown in our polytunnel and harvested young for tenderness. Versatile and beautiful — sauté the stems separately from the leaves, or use both together.",
    slug: "rainbow-chard-bunch",
    category: "vegetables",
    price: 350,
    unit: "large bunch (approx. 350g)",
    stock: 45,
    images: [
      "/images/rainbow-chard.jpg",
    ],
    dietary: ["vegan", "gluten-free", "dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "prod-7",
    producerId: "producer-1",
    producerName: "Fieldgate Farm Shop",
    producerSlug: "fieldgate-farm-shop",
    name: "New Season Garlic (3-bulb bundle)",
    description:
      "Fresh, uncured garlic harvested in July — the bulbs are plump, juicy, and far milder than the dried garlic most people are used to. Available for 4 weeks only each year. Use double the amount you normally would and adjust as you go — the flavour is sweeter and more delicate.",
    slug: "new-season-garlic-3-bulbs",
    category: "vegetables",
    price: 300,
    unit: "3 bulbs",
    stock: 35,
    images: [
      "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80",
    ],
    dietary: ["vegan", "gluten-free", "dairy-free"],
    allergens: [],
    seasonal: true,
    available: true,
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "prod-8",
    producerId: "producer-1",
    producerName: "Fieldgate Farm Shop",
    producerSlug: "fieldgate-farm-shop",
    name: "Dried Chilli Selection (mixed bag)",
    description:
      "A mixed bag of our home-grown dried chillies — varieties change each year but typically include Ancho, Guajillo, Mulato, and one or two surprises. Dried slowly at low temperature to preserve flavour and colour. Grind your own, rehydrate, or use whole in braises.",
    slug: "dried-chilli-selection",
    category: "preserves",
    price: 500,
    unit: "approx. 50g mixed bag",
    stock: 40,
    images: [
      "https://images.unsplash.com/photo-1518843875459-f738682238a6?w=800&q=80",
    ],
    dietary: ["vegan", "gluten-free", "dairy-free"],
    allergens: [],
    seasonal: true,
    available: true,
    createdAt: new Date("2024-02-01"),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    orderId: "order-1",
    consumerId: "consumer-1",
    consumerName: "Laura H.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "I've been on the weekly veg box for eight months and it's completely changed how I cook. The produce is extraordinary — the heritage tomatoes alone are worth the subscription. The recipe card every week is thoughtful and actually useful. Cannot recommend enough.",
    createdAt: new Date("2024-04-09"),
  },
  {
    id: "rev-2",
    orderId: "order-2",
    consumerId: "consumer-2",
    consumerName: "Chloe P.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "The wild garlic pesto is the best thing I've eaten all year — I ordered four jars when I saw it was seasonal and I'm rationing myself carefully. The eggs are also a revelation: deep orange yolks and a richness I've never got from supermarket eggs.",
    createdAt: new Date("2024-04-23"),
  },
  {
    id: "rev-3",
    orderId: "order-3",
    consumerId: "consumer-3",
    consumerName: "Neil S.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "The salad leaves arrived so fresh they lasted ten days in the fridge. I've never had that from a supermarket bag — they usually turn in three. The mix is genuinely interesting too, not just iceberg and romaine. Outstanding.",
    createdAt: new Date("2024-05-06"),
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "order-demo-1",
    consumerId: "consumer-1",
    consumerName: "Demo Customer",
    items: [
      {
        productId: "prod-1",
        productName: "Weekly Seasonal Veg Box (large)",
        producerId: "producer-1",
        producerName: "Fieldgate Farm Shop",
        price: 2200,
        quantity: 1,
        unit: "large box (10–12 items)",
        imageUrl: "/images/hero.jpg",
      },
      {
        productId: "prod-3",
        productName: "Free-Range Eggs (dozen)",
        producerId: "producer-1",
        producerName: "Fieldgate Farm Shop",
        price: 450,
        quantity: 2,
        unit: "dozen eggs",
        imageUrl: "/images/hero.jpg",
      },
    ],
    producerIds: ["producer-1"],
    status: "delivered",
    fulfilmentMethod: "delivery",
    deliveryAddress: {
      line1: "6 Adam & Eve Street",
      city: "Market Harborough",
      postcode: "LE16 7LT",
      country: "GB",
    },
    subtotal: 3100,
    commission: 0,
    deliveryFee: 295,
    total: 3395,
    stripePaymentIntentId: "pi_demo_produce_001",
    createdAt: new Date("2024-04-13"),
    updatedAt: new Date("2024-04-14"),
  },
];
